apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: "moviedb"        
  MYSQL_USER: "heem"  

---        
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_PASSWORD: "RXZyYWRlQDE5MDQ="
  MYSQL_ROOT_PASSWORD: "RXZyYWRlQDE5MDQ="

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: MYSQL_PASSWORD
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: MYSQL_ROOT_PASSWORD
    envFrom:
    - configMapRef:
        name: mysql-config

    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-storage      
  volumes:
  - name: mysql-storage
    persistentVolumeClaim:
      claimName: mysql-pvc



