apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config
data:
  DB_NAME: "moviedb"
  DB_USER: "root"
  DB_HOST: "mysql-service"
  PORT: "3000"  

---        
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: "RXZyYWRlQDE5MDQ="

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: evrademarc/backend:latest
          ports:
          - containerPort: 3000
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: node-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: node-config
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: node-config
                  key: DB_HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: node-config
                  key: PORT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  
  ports:
    - protocol: TCP
      port: 3000     
      targetPort: 3000  
  type: LoadBalancer  
          
